### ISSUE TITLE
NRE on WriteLine with newest package version?

### ISSUE THREAD

**Issue by WasabiFan** [poxet/tharga-console#3]
I just updated my NuGet packages for my project and discovered that the newest version of this library throws an exception when I call the `Console`'s `WriteLine` method. The exception is:

```
System.NullReferenceException was unhandled
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=Tharga.Toolkit.Console
  StackTrace:
       at Tharga.Toolkit.Console.Command.Base.InputManager.LinesInsertedEvent(Object sender, LinesInsertedEventArgs e)
       at Tharga.Toolkit.Console.Command.Base.SystemConsoleBase.InvokeLinesInsertedEvent(Int32 lineCount)
       at Tharga.Toolkit.Console.Command.Base.SystemConsoleBase.WriteLine(String value, OutputLevel level)
	   at ...
```

Is there something new that I need to call to initialize the console with this new version?

**Comment by poxet** [comment]
A plain and simple bug. When calling the console's WriteLine prior to using a command input this issue appeared.

This issue should be fixed by version 1.4.9 that is published on nuget.org now.
